version: '2'
services:
  bankfast:
    image: docker-registry.sandstone.com.au/unisys/bankfast_test:1.6
    environment:
      DB_HOST: ${db_host}
      DB_NAME: ${bankfast_db_name}
      DB_PASSWORD: ${bankfast_db_password}
      DB_USERNAME: ${bankfast_db_user}
      HOST_ENDPOINT: ${host_endpoint}
    stdin_open: true
    tty: true
    command:
    - /bin/sh
    - -c
    - /sst/scripts/start.sh
    labels:
      io.rancher.container.start_once: 'true'
  db:
    image: rancher/external-service
