version: '2'
services:
  apply2:
    scale: 1
    start_on_create: true
  uasadmin:
    scale: 1
    start_on_create: true
  lendfast:
    scale: 1
    start_on_create: true
  qas:
    external_ips:
    - 54.252.201.47
    start_on_create: true
  balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: /apply2
        priority: 1
        protocol: http
        service: apply2
        source_port: 80
        target_port: 8080
      - path: /apply
        priority: 2
        protocol: http
        service: apply
        source_port: 80
        target_port: 8080
      - path: /sandstone-apply-server
        priority: 3
        protocol: http
        service: apply
        source_port: 80
        target_port: 8080
      - path: /solr
        priority: 4
        protocol: http
        service: solr
        source_port: 80
        target_port: 8080
      - path: /elevate
        priority: 5
        protocol: http
        service: apply2
        source_port: 80
        target_port: 8080
      - path: /lendfast
        priority: 6
        protocol: http
        service: lendfast
        source_port: 80
        target_port: 8080
      - path: /creditdecisionservicewar
        priority: 7
        protocol: http
        service: lendfast
        source_port: 80
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  apply:
    scale: 1
    start_on_create: true
  csvfakehost:
    scale: 1
    start_on_create: true
  solr:
    scale: 1
    start_on_create: true
  lendfastfakehost:
    scale: 1
    start_on_create: true
  db:
    external_ips:
    - 51.140.163.112
    start_on_create: true
