version: '2'
services:
  bankfast:
    scale: 1
    start_on_create: true
  apache:
    scale: 1
    start_on_create: true
  balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: apache
        source_port: 80
        target_port: 80
      - priority: 2
        protocol: http
        service: bfsi
        source_port: 90
        target_port: 9080
      - priority: 3
        protocol: http
        service: liferay
        source_port: 8080
        target_port: 8080
      - priority: 5
        protocol: http
        service: rcas
        source_port: 9080
        target_port: 9080
      - priority: 6
        protocol: http
        service: bankfast
        source_port: 13588
        target_port: 13588
      - priority: 7
        protocol: http
        service: bankfast
        source_port: 13500
        target_port: 13500
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  bfsi:
    scale: 1
    start_on_create: true
  liferay:
    scale: 1
    start_on_create: true
  rcas:
    scale: 1
    start_on_create: true
  db:
    external_ips:
    - 51.140.163.112
    start_on_create: true
